spring:
  datasource:
    url: ${DATABASE_CONNECTION_STRING:jdbc:postgresql://localhost:5432/parking_meter}
    username: ${DB_USER:admin}
    password: ${DB_PASSWORD:admin}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
  flyway:
    enabled: true
    schemas: ["public"]
    locations: ["classpath:db/migrations", "classpath:db.migrations"]

server:
  port: 8080