spring:
  datasource:
    url: ${DATABASE_CONNECTION_STRING:jdbc:postgresql://localhost:5432/parking_meter}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:admin}
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: ${JPA_GENERATE_DDL:false}
    hibernate:
      use-new-id-generator-mappings: false
      ddl-auto: ${HIBERNATE_DDL_AUTO:create-drop}
    properties:
      hibernate:
        temp.use_jdbc_metadata_defaults: false
  cloud:
    refresh:
      refreshable: none
  cache:
    caffeine:
      spec: maximumSize=${CACHE_MAXIMUM_SIZE:100}, expireAfterWrite=${CACHE_TIME_IN_SECONDS:10}
  flyway:
    enabled: true
    schemas: ["public"]
    locations: ["classpath:db/migrations", "classpath:db.migrations"]

server:
  port: 8080